### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by HeroProtagonist** [jstastny/publish-gem-to-github#16]
Hi @jstastny,

I am facing the issue mentioned [here](https://github.com/jstastny/publish-gem-to-github/pull/14). The latest version of this package does not include the change, so I need to pin to master's sha. Wondering if you would be able to publish a new version. 

Thanks!

**Comment by jstastny** [comment]
Thanks for the reminder. I have just released https://github.com/jstastny/publish-gem-to-github/releases/tag/v2.4
