### ISSUE TITLE
Could we change the endpoint's working-directory logic?

### ISSUE THREAD

**Issue by mylanconnolly** [jstastny/publish-gem-to-github#4]
I am working in a project that contains multiple directories of source in it, some NPM modules some Gems, etc. I have tried to use this action to build and publish a Gem in it but ran across a failure of my application code being able to correctly require the Gem.

I was able to fix that by forking this action and modifying the logic in the last four lines of the endpoint as so:

```bash
# From this:
echo "Building the gem"
gem build ${WORKING_DIRECTORY:-.}/*.gemspec
echo "Pushing the built gem to GitHub Package Registry"
gem push --key github --host "https://rubygems.pkg.github.com/${OWNER}" ./*.gem

# To this:
cd "${WORKING_DIRECTORY:-.}"

echo "Building the gem"
gem build *.gemspec
echo "Pushing the built gem to GitHub Package Registry"
gem push --key github --host "https://rubygems.pkg.github.com/${OWNER}" ./*.gem
```

When building it the other way I had to modify the gemspec's files metadata to change the paths to be relative to the root of the repository, and that seems to have messed up the building of the Gem (where the import paths ended up being incorrect).

I can send a PR if this sounds good. Just wanted to check before I went ahead and did it.

Thanks!

**Comment by jstastny** [comment]
Hi @mylanconnolly!
Thanks a lot for the detailed report.

Your suggestion sounds very reasonable. If you have a PR, it would be great if you could share it.

Thanks in advance!

**Comment by mylanconnolly** [comment]
Created PR #5, thanks for considering it!
