### ISSUE TITLE
fatal: unsafe repository ('/github/workspace' is owned by someone else)

### ISSUE THREAD

**Issue by takayamaki** [jstastny/publish-gem-to-github#8]
Hi. Thank you for this action, it is very useful.

Today, I try to release my gem via this action. But it failed.
![image](https://user-images.githubusercontent.com/24884114/163330492-2ee277ce-d4d3-457f-8069-8b0e33ddb5f1.png)

It seems to occur by [this GitHub's change](https://github.blog/2022-04-12-git-security-vulnerability-announced/).

I think https://github.com/repo-sync/pull-request/issues/84 is a good reference to fix this issue.
Can you fix it?

Thanks!

**Comment by jstastny** [comment]
Should be resolved by #9

**Comment by jstastny** [comment]
The above mentioned fix is part of Release 2.1.

**Comment by takayamaki** [comment]
Thank you!
